name: PayShield Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  server-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Server Dependencies
      working-directory: ./src/server
      run: npm ci

    - name: Run Server Unit Tests
      working-directory: ./src/server
      run: npm run test | tee server-test.log

    - name: Upload Server Test Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: server-test-artifact
        path: src/server/server-test.log
        retention-days: 60
        overwrite: true

  client-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Client Dependencies
      working-directory: ./src/client
      run: npm ci

    - name: Run Client Unit Tests
      working-directory: ./src/client
      run: npm run test | tee client-test.log

    - name: Upload Client Test Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: client-test-artifact
        path: src/client/client-test.log
        retention-days: 60
        overwrite: true
